attic:
  STORAGE_MODE: db
  GIST_SYNC:
    URL: ''
    DIR: gist
    SYNC_INTERVAL_M: 10
  DB:
    FILE: ./db.json
  CONDUIT:
    HOST: localhost

clacks:
  CONDUIT:
    HOST: localhost

concierge:
  OPTIONS:
    ENSURED_WEBHOOKS:
      - url: /spotifyCallback
  CONDUIT:
    HOST: localhost
  SERVER:
    PORT: 4665

conduit:
  OPTIONS:
    FLEET:
      HOST: "localhost"
      DEVICE_TYPE: ''
    AUTH_ENABLED: false
  SERVER:
    PORT: 5959
  CONDUIT:
    TOKEN: ''
  CLACKS:
    SERVER: localhost

monitor:
  PLUGINS:
    - FILE_NAME: system-metrics.js
      EVERY: 1
    - FILE_NAME: disk-usage.js
      EVERY: 10
    - FILE_NAME: email-report.js
    - FILE_NAME: services.js
      EVERY: 10
      ARGS:
        HOST: localhost
  CONDUIT:
    HOST: localhost
  SES:
    TO_ADDRESS: ''
    SENDER_ADDRESS: ''
  AWS:
    ACCESS_KEY_ID: ''
    SECRET_ACCESS_KEY: ''

visuals:
  LEDS:
    ATTENUATION_FACTOR: 1
    BRIGHTNESS: 1
    USE_HARDWARE: false
    HARDWARE_TYPE: mote
  CONDUIT:
    HOST: localhost
  TEXT_DISPLAY:
    USE_HARDWARE: false
    HARDWARE_TYPE: pioled
  AUTH_ATTIC:
    HOST: ''
    KEY: /spotifyCallback
  SPOTIFY:
    CLIENT_ID: ''
    CLIENT_SECRET: ''
    CONCIERGE_IP: ''
    CONCIERGE_PORT: 4665

# Used only for node-common tests that call config.get()
testApp:
  DB:
    FILE: ./db.json
  CONDUIT:
    HOST: localhost
  GIST_SYNC:
    URL: https://gist.github.com/C-D-Lewis/b01d24df220ae0a8ece6f8c7ebc46d2b
    DIR: gist
    SYNC_INTERVAL_M: 5
  LEDS:
    ATTENUATION_FACTOR: 0.1
    BRIGHTNESS: 0.1
    USE_HARDWARE: false
    HARDWARE_TYPE: blinkt
  SERVER:
    PORT: 8989
  TEXT_DISPLAY:
    USE_HARDWARE: false
    HARDWARE_TYPE: pioled
  CLACKS:
    SERVER: localhost
  SES:
    TO_ADDRESS: ''
    SENDER_ADDRESS: ''
  AWS:
    ACCESS_KEY_ID: ''
    SECRET_ACCESS_KEY: ''
