# syntax=docker/dockerfile:1.4

FROM 'node:24-slim' AS base

# Install OS dependencies
RUN apt-get update && apt-get install -y git python3

FROM base

ENV DOCKER_TEST=1

WORKDIR /code

# Install app dependencies
ADD apps/conduit/package* /code/apps/conduit/
RUN cd /code/apps/conduit && npm ci
ADD apps/attic/package* /code/apps/attic/
RUN cd /code/apps/attic && npm ci
ADD apps/clacks/package* /code/apps/clacks/
RUN cd /code/apps/clacks && npm ci
ADD apps/concierge/package* /code/apps/concierge/
RUN cd /code/apps/concierge && npm ci
ADD apps/visuals/package* /code/apps/visuals/
RUN cd /code/apps/visuals && npm ci
ADD apps/monitor/package* /code/apps/monitor/
RUN cd /code/apps/monitor && npm ci

# Install common dependencies (could change most often)
ADD node-common/package* /code/node-common/
RUN cd /code/node-common && npm ci

# Add code
ADD apps/conduit/ /code/apps/conduit/
ADD apps/attic/ /code/apps/attic/
ADD apps/clacks/ /code/apps/clacks/
ADD apps/concierge/ /code/apps/concierge/
ADD apps/visuals/ /code/apps/visuals/
ADD apps/monitor/ /code/apps/monitor/
ADD node-common/ /code/node-common/

# Config cleanup
ADD config-default.yml /code/config-default.yml
RUN git config --global user.email "test@example.com" \
  && git config --global user.name "Test Name"

COPY <<EOF /code/apps/attic/db.json
{
  "conduit": {
    "users": {
      "value": [
        {
          "id": "f565b8c36fa89850e09f5ab3a651bb56",
          "name": "testUser",
          "permissions": ["all:all:all"],
          "hash": "800af9c9acb31ac36c561ed4e5a3da890398237de72dccb5e9419d63a384c2ee",
          "createdAt": 1684063071964
        },
        {
          "id": "f565b8c36fa89850e09f5ab3a651bb56",
          "name": "onlyMarvin",
          "permissions": [
            "Marvin:all:all"
          ],
          "hash": "aa992b2b6ca1046abed700f697cfaf593cfa3e338630dcae73480e897384c203",
          "createdAt": 1785584873494
        }
      ],
      "timestamp": 1684063071967
    }
  }
}
EOF

# Prepare tests
ADD tools/test-all.sh /code/tools/

CMD tools/test-all.sh
