version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: |
            cd node-common && npm ci
            cd ../apps/conduit && npm ci
            cd ../attic && npm ci
            cd ../visuals && npm ci
            cd ../ambience && npm ci
            cd ../concierge && npm ci
            cd ../spotify-auth && npm ci
            cd ../monitor && npm ci
      - run:
          name: 'Start core services'
          command: |
            pwd
            cd apps/conduit && npm start &
            pwd
            cd apps/attic && npm start &
