version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout

      - run:
          name: 'Install dependencies (node-common)'
          command: cd node-common && npm ci
      - run:
          name: 'Install dependencies (conduit)'
          command: cd apps/conduit && npm ci
      - run:
          name: 'Install dependencies (attic)'
          command: cd apps/attic && npm ci
      - run:
          name: 'Install dependencies (visuals)'
          command: cd apps/visuals && npm ci
      - run:
          name: 'Install dependencies (ambience)'
          command: cd apps/ambience && npm ci
      - run:
          name: 'Install dependencies (concierge)'
          command: cd apps/concierge && npm ci
      - run:
          name: 'Install dependencies (spotify-auth)'
          command: cd apps/spotify-auth && npm ci
      - run:
          name: 'Install dependencies (monitor)'
          command: cd apps/monitor && npm ci

      - run: cd tools && node runner.js conduit attic && cd ../apps/conduit && npm test
      # - run:
      #     name: 'Start service (conduit)'
      #     command: cd tools && node runner.js conduit
      # - run:
      #     name: 'Start service (attic)'
      #     command: cd tools && node runner.js attic

      # - run:
      #     name: 'npm test (conduit)'
      #     command: cd apps/conduit && npm test
      # - run:
      #     name: 'npm test (attic)'
      #     command: cd apps/attic && npm test
