version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          run: |
            'cd node-common && npm ci'
            'cd apps/conduit && npm ci'
            'cd apps/attic && npm ci'
            'cd apps/visuals && npm ci'
      - run:
          name: 'Start core services'
          run: |
            'cd apps/conduit && npm start &'
            'cd apps/attic && npm start &'
