LEDS:
  ATTENUATION_FACTOR: 1
  BRIGHTNESS: 1
  USE_HARDWARE: false
  HARDWARE_TYPE: mote
CONDUIT:
  HOST: localhost
TEXT_DISPLAY:
  USE_HARDWARE: false
  HARDWARE_TYPE: pioled
AUTH_ATTIC:
  HOST: ""
  KEY: /spotifyCallback
SPOTIFY:
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  CONCIERGE_IP: ""
  CONCIERGE_PORT: 4665
