name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: DOCKER_BUILDKIT=1 docker build -f Dockerfile.test -t node-microservices .  # Support heredoc
      - run: docker run -t node-microservices
